/*
 * Copyright (c) Velocity BPA, LLC
 * Licensed under the Business Source License 1.1
 * Commercial use requires a separate commercial license.
 * See LICENSE file for details.
 */

import {
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeConnectionType,
} from 'n8n-workflow';

import { createClientFromCredentials } from './transport/alloyClient';
import { executeEntityOperation, entityOperations, entityFields } from './actions/entity';
import { executeEvaluationOperation, evaluationOperations, evaluationFields } from './actions/evaluation';
import { executeJourneyOperation, journeyOperations, journeyFields } from './actions/journey';
import { executeResourceOperation } from './actions/router';

export class Alloy implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Alloy',
    name: 'alloy',
    icon: 'file:alloy.svg',
    group: ['transform'],
    version: 1,
    subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
    description: 'Interact with Alloy compliance orchestration platform for KYC, KYB, and fraud detection',
    defaults: { name: 'Alloy' },
    inputs: [NodeConnectionType.Main],
    outputs: [NodeConnectionType.Main],
    credentials: [{ name: 'alloyApi', required: true }],
    properties: [
      {
        displayName: 'Resource',
        name: 'resource',
        type: 'options',
        noDataExpression: true,
        options: [
          { name: 'Analytics', value: 'analytics' },
          { name: 'Application', value: 'application' },
          { name: 'Audit', value: 'audit' },
          { name: 'Business', value: 'business' },
          { name: 'Case', value: 'case' },
          { name: 'Decision', value: 'decision' },
          { name: 'Document', value: 'document' },
          { name: 'Entity', value: 'entity' },
          { name: 'Evaluation', value: 'evaluation' },
          { name: 'Event', value: 'event' },
          { name: 'Identity', value: 'identity' },
          { name: 'Integration', value: 'integration' },
          { name: 'Journey', value: 'journey' },
          { name: 'Report', value: 'report' },
          { name: 'Review', value: 'review' },
          { name: 'Risk', value: 'risk' },
          { name: 'Rule', value: 'rule' },
          { name: 'Tag', value: 'tag' },
          { name: 'User', value: 'user' },
          { name: 'Utility', value: 'utility' },
          { name: 'Watchlist', value: 'watchlist' },
          { name: 'Webhook', value: 'webhook' },
          { name: 'Workflow', value: 'workflow' },
        ],
        default: 'entity',
      },
      ...entityOperations,
      ...entityFields,
      ...evaluationOperations,
      ...evaluationFields,
      ...journeyOperations,
      ...journeyFields,
      // Application operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['application'] } },
        options: [
          { name: 'Archive', value: 'archive', action: 'Archive application' },
          { name: 'Create', value: 'create', action: 'Create application' },
          { name: 'Get', value: 'get', action: 'Get application' },
          { name: 'Get by External ID', value: 'getByExternalId', action: 'Get by external ID' },
          { name: 'Get Decision', value: 'getDecision', action: 'Get decision' },
          { name: 'Get Documents', value: 'getDocuments', action: 'Get documents' },
          { name: 'Get Events', value: 'getEvents', action: 'Get events' },
          { name: 'Get Status', value: 'getStatus', action: 'Get status' },
          { name: 'List', value: 'list', action: 'List applications' },
          { name: 'Submit', value: 'submit', action: 'Submit application' },
          { name: 'Update', value: 'update', action: 'Update application' },
        ],
        default: 'get',
      },
      // Document operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['document'] } },
        options: [
          { name: 'Delete', value: 'delete', action: 'Delete document' },
          { name: 'Get', value: 'get', action: 'Get document' },
          { name: 'Get by Entity', value: 'getByEntity', action: 'Get documents by entity' },
          { name: 'Get Data', value: 'getData', action: 'Get document data' },
          { name: 'Get Extracted Fields', value: 'getExtractedFields', action: 'Get extracted fields' },
          { name: 'Get Status', value: 'getStatus', action: 'Get document status' },
          { name: 'Get Verification', value: 'getVerification', action: 'Get verification result' },
          { name: 'List', value: 'list', action: 'List documents' },
          { name: 'Update', value: 'update', action: 'Update document' },
          { name: 'Upload', value: 'upload', action: 'Upload document' },
          { name: 'Verify', value: 'verify', action: 'Trigger verification' },
        ],
        default: 'upload',
      },
      // Identity operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['identity'] } },
        options: [
          { name: 'Get Attributes', value: 'getAttributes', action: 'Get identity attributes' },
          { name: 'Get Data', value: 'getData', action: 'Get identity data' },
          { name: 'Get History', value: 'getHistory', action: 'Get verification history' },
          { name: 'Get KYC Result', value: 'getKycResult', action: 'Get KYC result' },
          { name: 'Get Match', value: 'getMatch', action: 'Get identity match' },
          { name: 'Get Score', value: 'getScore', action: 'Get identity score' },
          { name: 'Get Verification', value: 'getVerification', action: 'Get verification' },
          { name: 'Get Watchlist Results', value: 'getWatchlistResults', action: 'Get watchlist results' },
          { name: 'Reverify', value: 'reverify', action: 'Reverify identity' },
          { name: 'Verify', value: 'verify', action: 'Verify identity' },
        ],
        default: 'verify',
      },
      // Business operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['business'] } },
        options: [
          { name: 'Get Address', value: 'getAddress', action: 'Get business address' },
          { name: 'Get Data', value: 'getData', action: 'Get business data' },
          { name: 'Get Documents', value: 'getDocuments', action: 'Get business documents' },
          { name: 'Get KYB Result', value: 'getKybResult', action: 'Get KYB result' },
          { name: 'Get Owners', value: 'getOwners', action: 'Get business owners' },
          { name: 'Get Registration', value: 'getRegistration', action: 'Get registration' },
          { name: 'Get Score', value: 'getScore', action: 'Get business score' },
          { name: 'Get Verification', value: 'getVerification', action: 'Get verification' },
          { name: 'Get Watchlist', value: 'getWatchlist', action: 'Get watchlist results' },
          { name: 'Verify', value: 'verify', action: 'Verify business' },
        ],
        default: 'verify',
      },
      // Watchlist operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['watchlist'] } },
        options: [
          { name: 'Confirm Hit', value: 'confirmHit', action: 'Confirm watchlist hit' },
          { name: 'Disable Monitoring', value: 'disableMonitoring', action: 'Disable ongoing monitoring' },
          { name: 'Dismiss Hit', value: 'dismissHit', action: 'Dismiss watchlist hit' },
          { name: 'Enable Monitoring', value: 'enableMonitoring', action: 'Enable ongoing monitoring' },
          { name: 'Get History', value: 'getHistory', action: 'Get screening history' },
          { name: 'Get Hit Details', value: 'getHitDetails', action: 'Get hit details' },
          { name: 'Get Hits', value: 'getHits', action: 'Get watchlist hits' },
          { name: 'Get Monitoring', value: 'getMonitoring', action: 'Get monitoring status' },
          { name: 'Get Sources', value: 'getSources', action: 'Get watchlist sources' },
          { name: 'Screen Business', value: 'screenBusiness', action: 'Screen business' },
          { name: 'Screen Entity', value: 'screenEntity', action: 'Screen entity' },
          { name: 'Screen Individual', value: 'screenIndividual', action: 'Screen individual' },
        ],
        default: 'screenEntity',
      },
      // Risk operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['risk'] } },
        options: [
          { name: 'Calculate', value: 'calculate', action: 'Calculate risk score' },
          { name: 'Get Assessment', value: 'getAssessment', action: 'Get risk assessment' },
          { name: 'Get Factors', value: 'getFactors', action: 'Get risk factors' },
          { name: 'Get History', value: 'getHistory', action: 'Get risk history' },
          { name: 'Get Level', value: 'getLevel', action: 'Get risk level' },
          { name: 'Get Rules', value: 'getRules', action: 'Get risk rules' },
          { name: 'Get Score', value: 'getScore', action: 'Get risk score' },
          { name: 'Get Signals', value: 'getSignals', action: 'Get risk signals' },
          { name: 'Get Threshold', value: 'getThreshold', action: 'Get risk threshold' },
          { name: 'Update Score', value: 'updateScore', action: 'Update risk score' },
        ],
        default: 'getScore',
      },
      // Decision operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['decision'] } },
        options: [
          { name: 'Approve', value: 'approve', action: 'Approve decision' },
          { name: 'Deny', value: 'deny', action: 'Deny decision' },
          { name: 'Escalate', value: 'escalate', action: 'Escalate decision' },
          { name: 'Get', value: 'get', action: 'Get decision' },
          { name: 'Get Audit', value: 'getAudit', action: 'Get decision audit' },
          { name: 'Get Factors', value: 'getFactors', action: 'Get decision factors' },
          { name: 'Get History', value: 'getHistory', action: 'Get decision history' },
          { name: 'Get Pending', value: 'getPending', action: 'Get pending decisions' },
          { name: 'Get Rules', value: 'getRules', action: 'Get decision rules' },
          { name: 'Override', value: 'override', action: 'Override decision' },
        ],
        default: 'get',
      },
      // Review operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['review'] } },
        options: [
          { name: 'Add Note', value: 'addNote', action: 'Add review note' },
          { name: 'Assign', value: 'assign', action: 'Assign review' },
          { name: 'Complete', value: 'complete', action: 'Complete review' },
          { name: 'Escalate', value: 'escalate', action: 'Escalate review' },
          { name: 'Get', value: 'get', action: 'Get review' },
          { name: 'Get History', value: 'getHistory', action: 'Get review history' },
          { name: 'Get Notes', value: 'getNotes', action: 'Get review notes' },
          { name: 'Get Pending', value: 'getPending', action: 'Get pending reviews' },
          { name: 'Get Queue', value: 'getQueue', action: 'Get review queue' },
          { name: 'Get Stats', value: 'getStats', action: 'Get review stats' },
        ],
        default: 'getQueue',
      },
      // Case operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['case'] } },
        options: [
          { name: 'Add Note', value: 'addNote', action: 'Add case note' },
          { name: 'Assign', value: 'assign', action: 'Assign case' },
          { name: 'Close', value: 'close', action: 'Close case' },
          { name: 'Create', value: 'create', action: 'Create case' },
          { name: 'Get', value: 'get', action: 'Get case' },
          { name: 'Get by Entity', value: 'getByEntity', action: 'Get cases by entity' },
          { name: 'Get Documents', value: 'getDocuments', action: 'Get case documents' },
          { name: 'Get History', value: 'getHistory', action: 'Get case history' },
          { name: 'Get Notes', value: 'getNotes', action: 'Get case notes' },
          { name: 'Get Status', value: 'getStatus', action: 'Get case status' },
          { name: 'Link Entity', value: 'linkEntity', action: 'Link entity to case' },
          { name: 'List', value: 'list', action: 'List cases' },
          { name: 'Update', value: 'update', action: 'Update case' },
        ],
        default: 'list',
      },
      // Workflow operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['workflow'] } },
        options: [
          { name: 'Execute', value: 'execute', action: 'Execute workflow' },
          { name: 'Get', value: 'get', action: 'Get workflow' },
          { name: 'Get All', value: 'getAll', action: 'Get all workflows' },
          { name: 'Get Config', value: 'getConfig', action: 'Get workflow config' },
          { name: 'Get Outcome', value: 'getOutcome', action: 'Get workflow outcome' },
          { name: 'Get Status', value: 'getStatus', action: 'Get execution status' },
          { name: 'Get Steps', value: 'getSteps', action: 'Get workflow steps' },
          { name: 'Get Version', value: 'getVersion', action: 'Get workflow version' },
        ],
        default: 'getAll',
      },
      // Rule operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['rule'] } },
        options: [
          { name: 'Get', value: 'get', action: 'Get rule' },
          { name: 'Get Actions', value: 'getActions', action: 'Get rule actions' },
          { name: 'Get Active', value: 'getActive', action: 'Get active rules' },
          { name: 'Get All', value: 'getAll', action: 'Get all rules' },
          { name: 'Get Conditions', value: 'getConditions', action: 'Get rule conditions' },
          { name: 'Get History', value: 'getHistory', action: 'Get rule history' },
          { name: 'Get Performance', value: 'getPerformance', action: 'Get rule performance' },
          { name: 'Test', value: 'test', action: 'Test rule' },
        ],
        default: 'getAll',
      },
      // Tag operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['tag'] } },
        options: [
          { name: 'Add', value: 'add', action: 'Add tag to entity' },
          { name: 'Create', value: 'create', action: 'Create tag' },
          { name: 'Delete', value: 'delete', action: 'Delete tag' },
          { name: 'Get All', value: 'getAll', action: 'Get all tags' },
          { name: 'Get by Entity', value: 'getByEntity', action: 'Get entity tags' },
          { name: 'Get Stats', value: 'getStats', action: 'Get tag stats' },
          { name: 'Remove', value: 'remove', action: 'Remove tag from entity' },
          { name: 'Search', value: 'search', action: 'Search by tag' },
        ],
        default: 'getAll',
      },
      // Event operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['event'] } },
        options: [
          { name: 'Export', value: 'export', action: 'Export events' },
          { name: 'Get', value: 'get', action: 'Get event' },
          { name: 'Get All', value: 'getAll', action: 'Get all events' },
          { name: 'Get by Entity', value: 'getByEntity', action: 'Get entity events' },
          { name: 'Get by Type', value: 'getByType', action: 'Get events by type' },
          { name: 'Get Timeline', value: 'getTimeline', action: 'Get event timeline' },
          { name: 'Get Types', value: 'getTypes', action: 'Get event types' },
          { name: 'Search', value: 'search', action: 'Search events' },
        ],
        default: 'getAll',
      },
      // Webhook operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['webhook'] } },
        options: [
          { name: 'Create', value: 'create', action: 'Create webhook' },
          { name: 'Delete', value: 'delete', action: 'Delete webhook' },
          { name: 'Get', value: 'get', action: 'Get webhook' },
          { name: 'Get Deliveries', value: 'getDeliveries', action: 'Get webhook deliveries' },
          { name: 'Get Events', value: 'getEvents', action: 'Get webhook events' },
          { name: 'List', value: 'list', action: 'List webhooks' },
          { name: 'Retry', value: 'retry', action: 'Retry delivery' },
          { name: 'Test', value: 'test', action: 'Test webhook' },
          { name: 'Update', value: 'update', action: 'Update webhook' },
        ],
        default: 'list',
      },
      // Report operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['report'] } },
        options: [
          { name: 'Download', value: 'download', action: 'Download report' },
          { name: 'Generate', value: 'generate', action: 'Generate report' },
          { name: 'Get', value: 'get', action: 'Get report' },
          { name: 'Get Compliance', value: 'getCompliance', action: 'Get compliance report' },
          { name: 'Get Risk', value: 'getRisk', action: 'Get risk report' },
          { name: 'Get Status', value: 'getStatus', action: 'Get report status' },
          { name: 'Get Templates', value: 'getTemplates', action: 'Get report templates' },
          { name: 'Get Volume', value: 'getVolume', action: 'Get volume report' },
          { name: 'List', value: 'list', action: 'List reports' },
          { name: 'Schedule', value: 'schedule', action: 'Schedule report' },
        ],
        default: 'list',
      },
      // Audit operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['audit'] } },
        options: [
          { name: 'Export', value: 'export', action: 'Export audit log' },
          { name: 'Get Access', value: 'getAccess', action: 'Get access audit' },
          { name: 'Get by Entity', value: 'getByEntity', action: 'Get audit by entity' },
          { name: 'Get by User', value: 'getByUser', action: 'Get audit by user' },
          { name: 'Get Compliance', value: 'getCompliance', action: 'Get compliance audit' },
          { name: 'Get Events', value: 'getEvents', action: 'Get audit events' },
          { name: 'Get Log', value: 'getLog', action: 'Get audit log' },
          { name: 'Search', value: 'search', action: 'Search audit log' },
        ],
        default: 'getLog',
      },
      // Integration operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['integration'] } },
        options: [
          { name: 'Get All', value: 'getAll', action: 'Get all integrations' },
          { name: 'Get Config', value: 'getConfig', action: 'Get integration config' },
          { name: 'Get Data Sources', value: 'getDataSources', action: 'Get data sources' },
          { name: 'Get Provider Status', value: 'getProviderStatus', action: 'Get provider status' },
          { name: 'Get Providers', value: 'getProviders', action: 'Get available providers' },
          { name: 'Get Status', value: 'getStatus', action: 'Get integration status' },
          { name: 'Test', value: 'test', action: 'Test integration' },
        ],
        default: 'getAll',
      },
      // Analytics operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['analytics'] } },
        options: [
          { name: 'Export', value: 'export', action: 'Export analytics' },
          { name: 'Get Application Stats', value: 'getApplicationStats', action: 'Get application stats' },
          { name: 'Get Approval Rate', value: 'getApprovalRate', action: 'Get approval rate' },
          { name: 'Get Dashboard', value: 'getDashboard', action: 'Get dashboard stats' },
          { name: 'Get Funnel', value: 'getFunnel', action: 'Get conversion funnel' },
          { name: 'Get Rejection Rate', value: 'getRejectionRate', action: 'Get rejection rate' },
          { name: 'Get Review Time', value: 'getReviewTime', action: 'Get review time' },
          { name: 'Get Risk Distribution', value: 'getRiskDistribution', action: 'Get risk distribution' },
          { name: 'Get Volume', value: 'getVolume', action: 'Get volume trends' },
        ],
        default: 'getDashboard',
      },
      // User operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['user'] } },
        options: [
          { name: 'Create', value: 'create', action: 'Create user' },
          { name: 'Delete', value: 'delete', action: 'Delete user' },
          { name: 'Get', value: 'get', action: 'Get user' },
          { name: 'Get Activity', value: 'getActivity', action: 'Get user activity' },
          { name: 'Get All', value: 'getAll', action: 'Get all users' },
          { name: 'Get Permissions', value: 'getPermissions', action: 'Get user permissions' },
          { name: 'Update', value: 'update', action: 'Update user' },
          { name: 'Update Role', value: 'updateRole', action: 'Update user role' },
        ],
        default: 'getAll',
      },
      // Utility operations
      { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
        displayOptions: { show: { resource: ['utility'] } },
        options: [
          { name: 'Get API Status', value: 'getApiStatus', action: 'Get API status' },
          { name: 'Get Document Requirements', value: 'getDocumentRequirements', action: 'Get document requirements' },
          { name: 'Get Rate Limits', value: 'getRateLimits', action: 'Get rate limits' },
          { name: 'Get SDK Version', value: 'getSdkVersion', action: 'Get SDK version' },
          { name: 'Get Supported Countries', value: 'getSupportedCountries', action: 'Get supported countries' },
          { name: 'Get Supported Documents', value: 'getSupportedDocuments', action: 'Get supported documents' },
          { name: 'Test Connection', value: 'testConnection', action: 'Test connection' },
          { name: 'Validate API Key', value: 'validateApiKey', action: 'Validate API key' },
        ],
        default: 'testConnection',
      },
      // Common fields
      { displayName: 'Entity Token', name: 'entityToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['document', 'watchlist', 'risk', 'tag', 'event', 'case', 'audit', 'application'],
          operation: ['getByEntity', 'screenEntity', 'getAssessment', 'getScore', 'getFactors', 'getLevel', 'getHistory', 'getSignals', 'add', 'remove', 'getTimeline', 'linkEntity', 'getMonitoring', 'enableMonitoring', 'disableMonitoring', 'create'] } },
        default: '', description: 'The unique token of the entity' },
      { displayName: 'Document Token', name: 'documentToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['document'], operation: ['get', 'delete', 'getStatus', 'getVerification', 'getData', 'getExtractedFields', 'verify', 'update'] } },
        default: '', description: 'The unique token of the document' },
      { displayName: 'Verification Token', name: 'verificationToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['identity', 'business'], operation: ['getVerification', 'getMatch', 'getData', 'getWatchlistResults', 'getKycResult', 'getScore', 'getAttributes', 'getHistory', 'reverify', 'getOwners', 'getDocuments', 'getWatchlist', 'getKybResult', 'getRegistration', 'getAddress'] } },
        default: '', description: 'The verification token' },
      { displayName: 'Screening Token', name: 'screeningToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['watchlist'], operation: ['getHits', 'getHitDetails', 'dismissHit', 'confirmHit'] } },
        default: '', description: 'The screening token' },
      { displayName: 'Hit ID', name: 'hitId', type: 'string', required: true,
        displayOptions: { show: { resource: ['watchlist'], operation: ['getHitDetails', 'dismissHit', 'confirmHit'] } },
        default: '', description: 'The watchlist hit ID' },
      { displayName: 'Decision Token', name: 'decisionToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['decision'], operation: ['get', 'getRules', 'getFactors', 'override', 'approve', 'deny', 'escalate', 'getAudit'] } },
        default: '', description: 'The decision token' },
      { displayName: 'Review Token', name: 'reviewToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['review'], operation: ['get', 'assign', 'complete', 'addNote', 'getNotes', 'escalate'] } },
        default: '', description: 'The review token' },
      { displayName: 'Case Token', name: 'caseToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['case'], operation: ['get', 'update', 'close', 'assign', 'getHistory', 'addNote', 'getNotes', 'getDocuments', 'linkEntity', 'getStatus'] } },
        default: '', description: 'The case token' },
      { displayName: 'Workflow Token', name: 'workflowToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['workflow'], operation: ['get', 'getSteps', 'getOutcome', 'getVersion', 'execute', 'getConfig'] } },
        default: '', description: 'The workflow token' },
      { displayName: 'Execution Token', name: 'executionToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['workflow'], operation: ['getStatus'] } },
        default: '', description: 'The workflow execution token' },
      { displayName: 'Rule ID', name: 'ruleId', type: 'string', required: true,
        displayOptions: { show: { resource: ['rule'], operation: ['get', 'getConditions', 'getActions', 'test', 'getPerformance', 'getHistory'] } },
        default: '', description: 'The rule ID' },
      { displayName: 'Tag ID', name: 'tagId', type: 'string', required: true,
        displayOptions: { show: { resource: ['tag'], operation: ['delete'] } },
        default: '', description: 'The tag ID' },
      { displayName: 'Tag Name', name: 'tagName', type: 'string', required: true,
        displayOptions: { show: { resource: ['tag'], operation: ['add', 'remove'] } },
        default: '', description: 'The tag name' },
      { displayName: 'Event ID', name: 'eventId', type: 'string', required: true,
        displayOptions: { show: { resource: ['event'], operation: ['get'] } },
        default: '', description: 'The event ID' },
      { displayName: 'Event Type', name: 'eventType', type: 'string',
        displayOptions: { show: { resource: ['event'], operation: ['getByType'] } },
        default: '', description: 'The event type to filter by' },
      { displayName: 'Webhook ID', name: 'webhookId', type: 'string', required: true,
        displayOptions: { show: { resource: ['webhook'], operation: ['get', 'update', 'delete', 'test', 'getEvents', 'getDeliveries', 'retry'] } },
        default: '', description: 'The webhook ID' },
      { displayName: 'Delivery ID', name: 'deliveryId', type: 'string', required: true,
        displayOptions: { show: { resource: ['webhook'], operation: ['retry'] } },
        default: '', description: 'The delivery ID to retry' },
      { displayName: 'Report ID', name: 'reportId', type: 'string', required: true,
        displayOptions: { show: { resource: ['report'], operation: ['get', 'getStatus', 'download'] } },
        default: '', description: 'The report ID' },
      { displayName: 'User ID', name: 'userId', type: 'string', required: true,
        displayOptions: { show: { resource: ['user', 'audit', 'review', 'case'], operation: ['get', 'update', 'delete', 'getPermissions', 'updateRole', 'getActivity', 'getByUser', 'assign'] } },
        default: '', description: 'The user ID' },
      { displayName: 'Integration ID', name: 'integrationId', type: 'string', required: true,
        displayOptions: { show: { resource: ['integration'], operation: ['getStatus', 'test', 'getConfig'] } },
        default: '', description: 'The integration ID' },
      { displayName: 'Provider ID', name: 'providerId', type: 'string', required: true,
        displayOptions: { show: { resource: ['integration'], operation: ['getProviderStatus'] } },
        default: '', description: 'The provider ID' },
      { displayName: 'Application Token', name: 'applicationToken', type: 'string', required: true,
        displayOptions: { show: { resource: ['application'], operation: ['get', 'update', 'submit', 'getStatus', 'getDecision', 'getDocuments', 'getEvents', 'archive'] } },
        default: '', description: 'The application token' },
      { displayName: 'External ID', name: 'externalId', type: 'string', required: true,
        displayOptions: { show: { resource: ['application'], operation: ['getByExternalId'] } },
        default: '', description: 'Your external identifier' },
      // Data input fields
      { displayName: 'Entity Data', name: 'entityData', type: 'json',
        displayOptions: { show: { resource: ['identity'], operation: ['verify'] } },
        default: '{\n  "name_first": "",\n  "name_last": "",\n  "birth_date": "",\n  "address_line_1": "",\n  "address_city": "",\n  "address_state": "",\n  "address_postal_code": "",\n  "address_country_code": "US"\n}',
        description: 'Entity data for identity verification' },
      { displayName: 'Business Data', name: 'businessData', type: 'json',
        displayOptions: { show: { resource: ['business', 'watchlist'], operation: ['verify', 'screenBusiness'] } },
        default: '{\n  "business_name": "",\n  "business_ein": ""\n}',
        description: 'Business data for verification' },
      { displayName: 'Individual Data', name: 'individualData', type: 'json',
        displayOptions: { show: { resource: ['watchlist'], operation: ['screenIndividual'] } },
        default: '{\n  "name_first": "",\n  "name_last": "",\n  "birth_date": ""\n}',
        description: 'Individual data for watchlist screening' },
      { displayName: 'Document Type', name: 'documentType', type: 'options',
        displayOptions: { show: { resource: ['document'], operation: ['upload'] } },
        options: [
          { name: 'Passport', value: 'passport' },
          { name: "Driver's License", value: 'drivers_license' },
          { name: 'National ID', value: 'national_id' },
          { name: 'Utility Bill', value: 'utility_bill' },
          { name: 'Selfie', value: 'selfie' },
        ],
        default: 'drivers_license', description: 'The type of document' },
      { displayName: 'Binary Property', name: 'binaryProperty', type: 'string',
        displayOptions: { show: { resource: ['document'], operation: ['upload'] } },
        default: 'data', description: 'Binary property containing the file' },
      { displayName: 'Side', name: 'side', type: 'options',
        displayOptions: { show: { resource: ['document'], operation: ['upload'] } },
        options: [{ name: 'Front', value: 'front' }, { name: 'Back', value: 'back' }, { name: 'N/A', value: '' }],
        default: '', description: 'Document side' },
      { displayName: 'Decision', name: 'decision', type: 'options', required: true,
        displayOptions: { show: { resource: ['review'], operation: ['complete'] } },
        options: [{ name: 'Approve', value: 'approved' }, { name: 'Deny', value: 'denied' }],
        default: 'approved', description: 'The review decision' },
      { displayName: 'Reason', name: 'reason', type: 'string',
        displayOptions: { show: { resource: ['watchlist', 'decision', 'review', 'case'], operation: ['dismissHit', 'approve', 'deny', 'escalate', 'complete'] } },
        default: '', description: 'Reason for the action' },
      { displayName: 'Note', name: 'note', type: 'string', typeOptions: { rows: 4 },
        displayOptions: { show: { resource: ['review', 'case'], operation: ['addNote'] } },
        default: '', description: 'Note to add' },
      { displayName: 'Resolution', name: 'resolution', type: 'string',
        displayOptions: { show: { resource: ['case'], operation: ['close'] } },
        default: '', description: 'Resolution notes' },
      { displayName: 'Role', name: 'role', type: 'string',
        displayOptions: { show: { resource: ['user'], operation: ['updateRole'] } },
        default: '', description: 'The role to assign' },
      { displayName: 'Query', name: 'query', type: 'string',
        displayOptions: { show: { resource: ['tag', 'event', 'audit'], operation: ['search'] } },
        default: '', description: 'Search query' },
      { displayName: 'Version', name: 'version', type: 'string',
        displayOptions: { show: { resource: ['workflow'], operation: ['getVersion'] } },
        default: 'latest', description: 'The workflow version' },
      // JSON data fields
      { displayName: 'Application Data', name: 'applicationData', type: 'json',
        displayOptions: { show: { resource: ['application'], operation: ['create'] } },
        default: '{}', description: 'Application data' },
      { displayName: 'Update Data', name: 'updateData', type: 'json',
        displayOptions: { show: { resource: ['application', 'document', 'case', 'webhook', 'user'], operation: ['update'] } },
        default: '{}', description: 'Data to update' },
      { displayName: 'Case Data', name: 'caseData', type: 'json',
        displayOptions: { show: { resource: ['case'], operation: ['create'] } },
        default: '{"title": "", "description": ""}', description: 'Case data' },
      { displayName: 'Webhook Data', name: 'webhookData', type: 'json',
        displayOptions: { show: { resource: ['webhook'], operation: ['create'] } },
        default: '{"url": "", "events": []}', description: 'Webhook configuration' },
      { displayName: 'User Data', name: 'userData', type: 'json',
        displayOptions: { show: { resource: ['user'], operation: ['create'] } },
        default: '{"email": "", "name": ""}', description: 'User data' },
      { displayName: 'Tag Data', name: 'tagData', type: 'json',
        displayOptions: { show: { resource: ['tag'], operation: ['create'] } },
        default: '{"name": ""}', description: 'Tag data' },
      { displayName: 'Report Data', name: 'reportData', type: 'json',
        displayOptions: { show: { resource: ['report'], operation: ['generate'] } },
        default: '{"type": "compliance"}', description: 'Report configuration' },
      { displayName: 'Schedule Data', name: 'scheduleData', type: 'json',
        displayOptions: { show: { resource: ['report'], operation: ['schedule'] } },
        default: '{"type": "compliance", "frequency": "weekly"}', description: 'Schedule configuration' },
      { displayName: 'Override Data', name: 'overrideData', type: 'json',
        displayOptions: { show: { resource: ['decision'], operation: ['override'] } },
        default: '{"new_outcome": "approved", "reason": ""}', description: 'Override data' },
      { displayName: 'Score Data', name: 'scoreData', type: 'json',
        displayOptions: { show: { resource: ['risk'], operation: ['updateScore'] } },
        default: '{"score": 50}', description: 'Risk score data' },
      { displayName: 'Calculation Data', name: 'calculationData', type: 'json',
        displayOptions: { show: { resource: ['risk'], operation: ['calculate'] } },
        default: '{}', description: 'Data for risk calculation' },
      { displayName: 'Test Data', name: 'testData', type: 'json',
        displayOptions: { show: { resource: ['rule'], operation: ['test'] } },
        default: '{}', description: 'Test data for rule' },
      { displayName: 'Execution Data', name: 'executionData', type: 'json',
        displayOptions: { show: { resource: ['workflow'], operation: ['execute'] } },
        default: '{}', description: 'Data for workflow execution' },
      { displayName: 'Export Parameters', name: 'exportParams', type: 'json',
        displayOptions: { show: { resource: ['event', 'audit', 'analytics'], operation: ['export'] } },
        default: '{"format": "csv"}', description: 'Export parameters' },
      { displayName: 'Return All', name: 'returnAll', type: 'boolean',
        displayOptions: { show: { resource: ['application', 'case'], operation: ['list'] } },
        default: false, description: 'Whether to return all results' },
      { displayName: 'Limit', name: 'limit', type: 'number',
        displayOptions: { show: { resource: ['application', 'case'], operation: ['list'], returnAll: [false] } },
        typeOptions: { minValue: 1, maxValue: 100 }, default: 25 },
      { displayName: 'Filters', name: 'filters', type: 'collection', placeholder: 'Add Filter',
        displayOptions: { show: { resource: ['application', 'case'], operation: ['list'] } },
        default: {}, options: [
          { displayName: 'Status', name: 'status', type: 'string', default: '' },
          { displayName: 'Created After', name: 'created_after', type: 'string', default: '' },
          { displayName: 'Created Before', name: 'created_before', type: 'string', default: '' },
        ] },
    ],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const items = this.getInputData();
    const returnData: INodeExecutionData[] = [];
    const resource = this.getNodeParameter('resource', 0) as string;
    const operation = this.getNodeParameter('operation', 0) as string;
    const client = await createClientFromCredentials(this);

    for (let i = 0; i < items.length; i++) {
      try {
        let results: INodeExecutionData[];
        switch (resource) {
          case 'entity':
            results = await executeEntityOperation(this, client, operation, i);
            break;
          case 'evaluation':
            results = await executeEvaluationOperation(this, client, operation, i);
            break;
          case 'journey':
            results = await executeJourneyOperation(this, client, operation, i);
            break;
          default:
            results = await executeResourceOperation(this, client, resource, operation, i);
        }
        returnData.push(...results);
      } catch (error: any) {
        if (this.continueOnFail()) {
          returnData.push({ json: { error: error.message, resource, operation }, pairedItem: { item: i } });
          continue;
        }
        throw error;
      }
    }
    return [returnData];
  }
}
